// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqCjGgQpnEyIfBrT4eXr6y8OIZVQALcmY',
    appId: '1:932861188678:web:512c08d1f7ccca3da5c847',
    messagingSenderId: '932861188678',
    projectId: 'ostad-flutter-71eb6',
    authDomain: 'ostad-flutter-71eb6.firebaseapp.com',
    storageBucket: 'ostad-flutter-71eb6.appspot.com',
    measurementId: 'G-3G2W97PRNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArzDziKy4YKCq-j649FX5rgm2YPMxjdT0',
    appId: '1:932861188678:android:a08b308feaefd2d2a5c847',
    messagingSenderId: '932861188678',
    projectId: 'ostad-flutter-71eb6',
    storageBucket: 'ostad-flutter-71eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHoUV_14CJ7O9SYtvuACfQZW8EHAupuro',
    appId: '1:932861188678:ios:f196f36993d4450ea5c847',
    messagingSenderId: '932861188678',
    projectId: 'ostad-flutter-71eb6',
    storageBucket: 'ostad-flutter-71eb6.appspot.com',
    iosBundleId: 'com.ayman.ostadapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHoUV_14CJ7O9SYtvuACfQZW8EHAupuro',
    appId: '1:932861188678:ios:f196f36993d4450ea5c847',
    messagingSenderId: '932861188678',
    projectId: 'ostad-flutter-71eb6',
    storageBucket: 'ostad-flutter-71eb6.appspot.com',
    iosBundleId: 'com.ayman.ostadapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqCjGgQpnEyIfBrT4eXr6y8OIZVQALcmY',
    appId: '1:932861188678:web:81915ee14bcc7a3ea5c847',
    messagingSenderId: '932861188678',
    projectId: 'ostad-flutter-71eb6',
    authDomain: 'ostad-flutter-71eb6.firebaseapp.com',
    storageBucket: 'ostad-flutter-71eb6.appspot.com',
    measurementId: 'G-EMD54QLP08',
  );
}
